# collabnotes/docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:14-alpine
    container_name: collabnotes_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: 
      context: ./user_service
      dockerfile: Dockerfile
    container_name: collabnotes_user_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Same environment variables as your .env, but adapted for containers
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/users_db
      SECRET_KEY: some_super_secret_key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    # This runs your uvicorn command from the Dockerfile CMD